package br.com.supermercados.prices.admin;

public enum AdminAction {
    SOURCE_REGISTERED,
    SOURCE_STATUS_CHANGED,
    CHAIN_INGESTED,
    STORE_INGESTED,
    PRODUCT_INGESTED,
    PRICE_RECORDED,
    CONTRIBUTION_APPROVED,
    CONTRIBUTION_REJECTED
}
